Css fix
TheColdVoid/RandomListApp pull request #5
Opened 2019-07-17 16:43 UTC by ShepherXD

2019-07-18 05:29 UTC, TheColdVoid requested changes
一个小的修改建议

2019-07-18 05:29 UTC, TheColdVoid commented on main.js
> +    'curr-list': {
这个其实不是一个list 而是list中的一个项（item）或许叫goItem更好吧

2019-07-18 05:29 UTC, TheColdVoid commented on index.html
> +          style="margin:0 0 0 6vmax;color:rgb(32, 139, 182)">
这个颜色好评

2019-07-18 06:15 UTC, ShepherXD commented
因为你之前说你超喜欢这个绿色的啦23333------------------ 原始邮件 ------------------
发件人: "TheColdVoid"<notifications@github.com>
发送时间: 2019年7月18日(星期四) 中午1:29
收件人: "TheColdVoid/RandomListApp"<RandomListApp@noreply.github.com>;
抄送: "ShepherXD"<1046019173@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [TheColdVoid/RandomListApp] Css fix (#5)



@TheColdVoid requested changes on this pull request.
 
一个小的修改建议

 
In index.html:
 >          <v-icon dark>done</v-icon>        </v-btn>        <hr>        </hr>        <section>          <article id="randomlist"> -          <random-list  v-for="item in currList" :go="item" @remove-go="removeGo"> +          <v-icon color="teal lighten-2" large>sentiment_dissatisfied</v-icon> +          <random-list  v-for="item in currList" :go="item" @remove-go="removeGo" +          style="margin:0 0 0 15%;color:rgb(32, 139, 182)">  
这个颜色还可以
 
 
In main.js:
 > @@ -8,14 +8,18 @@ var vm = new Vue({      count: 1    },    components: { -    'random-list': { +    'curr-list': {  
这个其实不是一个list 而是list中的一个项（item）或许叫goItem更好吧
 
 
In index.html:
 >          <v-icon dark>done</v-icon>        </v-btn>        <hr>        </hr>        <section>          <article id="randomlist"> -          <random-list  v-for="item in currList" :go="item" @remove-go="removeGo"> -          </random-list> +          <v-icon color="teal lighten-2" large>sentiment_dissatisfied</v-icon> +          <curr-list  v-for="item in currList" :go="item" @remove-go="removeGo" +          style="margin:0 0 0 6vmax;color:rgb(32, 139, 182)">  
这个颜色好评
 
&mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

2019-07-18 06:16 UTC, TheColdVoid commented
诶嘿~

2019-07-19 12:24 UTC, TheColdVoid approved these changes

2019-07-19 12:24 UTC, merged